services:
  web:
    build: .
    container_name: suma_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-suma}
      MYSQL_USER: ${MYSQL_USER:-suma_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-suma_pass}
      # You can set SUMASERVER_URL & SUMA_REPORTS_URL here if needed or in the env file
    env_file:
      - .env

  db:
    image: mysql:8.4
    container_name: suma_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_pass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-suma}
      MYSQL_USER: ${MYSQL_USER:-suma_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-suma_pass}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: {}
